"""CCF 推荐国际学术会议/期刊目录（2022 版，自动解析自 PDF）.

CCF_CONF: 会议简称 -> [全称, 类别(A/B/C)]
CCF_JOURN: 期刊简称 -> [全称, 类别(A/B/C)]
"""

CCF_CONF = {
    "3DV": ("International Conference on 3D Vision", "C"),
    "AAAI": ("AAAI Conference on Artificial Intelligence", "A"),
    "AAMAS": ("International Joint Conference on Autonomous Agents and Multi- agent Systems", "B"),
    "ACCV": ("Asian Conference on Computer Vision", "C"),
    "ACISP": ("Australasia Conference on Information Security and Privacy", "C"),
    "ACL": ("Annual Meeting of the Association for Computational Linguistics", "A"),
    "ACM MM": ("ACM International Conference on Multimedia", "A"),
    "ACML": ("Asian Conference on Machine Learning", "C"),
    "ACNS": ("International Conference on Applied Cryptography and Network Security", "C"),
    "ACSAC": ("Annual Computer Security Applications Conference", "B"),
    "ADMA": ("International Conference on Advanced Data Mining and Applications", "C"),
    "AISTATS": ("International Conference on Artificial Intelligence and Statistics", "C"),
    "ALT": ("International Conference on Algorithmic Learning Theory", "C"),
    "AMIA": ("American Medical Informatics Association Annual Symposium", "C"),
    "ANCS": ("ACM/IEEE Symposium on Architectures for Networking and Communication Systems", "C"),
    "APBC": ("Asia Pacific Bioinformatics Conference", "C"),
    "APLAS": ("Asian Symposium on Programming Languages and Systems", "C"),
    "APNOMS": ("Asia-Pacific Network Operations and Management Symposium", "C"),
    "APNet": ("Asia-Pacific Workshop on Networking", "C"),
    "APSEC": ("Asia-Pacific Software Engineering Conference", "C"),
    "APWeb": ("Asia Pacific Web Conference", "C"),
    "ASAP": ("IEEE International Conference on Application-Specific Systems, Architectures, and Processors", "C"),
    "ASE": ("International Conference on Automated Software Engineering", "A"),
    "ASIACRYPT": ("Annual International Conference on the Theory and Application of Cryptology and Information Security", "B"),
    "ASP-DAC": ("Asia and South Pacific Design Automation Conference", "C"),
    "ASPLOS": ("International Conference on Architectural Support for Programming Languages and Operating Systems", "A"),
    "ASSETS": ("International ACM SIGACCESS Conference on Computers and Accessibility", "C"),
    "ATS": ("IEEE Asian Test Symposium", "C"),
    "ATVA": ("International Symposium on Automated Technology for Verification and Analysis", "C"),
    "AVI": ("International Working Conference on Advanced Visual Interfaces", "C"),
    "AsiaCCS": ("ACM Asia Conference on Computer and Communications Security", "C"),
    "BIBM": ("IEEE International Conference on Bioinformatics and Biomedicine", "B"),
    "BIT": ("Behaviour & Information Technology", "C"),
    "BMVC": ("British Machine Vision Conference", "C"),
    "CAD/Graphics": ("International Conference on Computer-Aided Design and Computer Graphics", "C"),
    "CASA": ("International Conference on Computer Animation and Social Agents", "C"),
    "CASES": ("International Conference on Compilers, Architectures, and Synthesis for Embedded Systems", "C"),
    "CAV": ("International Conference on Computer Aided Verification", "A"),
    "CAiSE": ("International Conference on Advanced Information Systems Engineering", "B"),
    "CCC": ("Conference on Computational Complexity", "B"),
    "CCGRID": ("IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing", "C"),
    "CCS": ("ACM Conference on Computer and Communications Security", "A"),
    "CF": ("ACM International Conference on Computing Frontiers", "C"),
    "CGI": ("Computer Graphics International", "C"),
    "CGO": ("The International Symposium on Code Generation and Optimization", "B"),
    "CHES": ("International Conference on Cryptographic Hardware and Embedded Systems", "B"),
    "CHI": ("ACM Conference on Human Factors in Computing Systems", "A"),
    "CIDR": ("Conference on Innovative Data Systems Research", "B"),
    "CIKM": ("ACM International Conference on Information and Knowledge Management", "B"),
    "CLUSTER": ("IEEE International Conference on Cluster Computing", "B"),
    "COCOON": ("International Computing and Combinatorics Conference", "B"),
    "CODES+ISSS": ("International Conference on Hardware/Software Co-design and System Synthesis", "B"),
    "COLING": ("International Conference on Computational Linguistics", "B"),
    "COLT": ("Annual Conference on Computational Learning Theory", "B"),
    "COMPSAC": ("International Computer Software and Applications Conference", "C"),
    "CONCUR": ("International Conference on Concurrency Theory", "B"),
    "COSIT": ("International Conference on Spatial Information Theory", "C"),
    "CP": ("International Conference on Principles and Practice of Constraint Programming", "B"),
    "CRYPTO": ("International Cryptology Conference", "A"),
    "CSCW": ("Computer Supported Cooperative Work", "B"),
    "CSCWD": ("International Conference on Computer Supported Cooperative Work in Design", "C"),
    "CSFW": ("IEEE Computer Security Foundations Workshop", "B"),
    "CSL": ("Computer Science Logic", "C"),
    "CT-RSA": ("The Cryptographer's Track at RSA Conference", "C"),
    "CVM": ("Computational Visual Media", "C"),
    "CVPR": ("IEEE/CVF Computer Vision and Pattern Recognition Conference", "A"),
    "CoNEXT": ("ACM International Conference on Emerging Networking Experiments and Technologies", "B"),
    "CoNLL": ("Conference on Computational Natural Language Learning", "C"),
    "CogSci": ("Annual Meeting of the Cognitive Science Society", "B"),
    "CollaborateCom": ("International Conference on Collaborative Computing: Networking, Applications and Worksharing", "C"),
    "CoopIS": ("International Conference on Cooperative Information Systems", "C"),
    "DAC": ("Design Automation Conference", "A"),
    "DASFAA": ("International Conference on Database Systems for Advanced Applications", "B"),
    "DATE": ("Design, Automation & Test in Europe", "B"),
    "DCC": ("Data Compression Conference", "B"),
    "DEXA": ("International Conference on Database and Expert System Applications", "C"),
    "DFRWS": ("Digital Forensic Research Workshop", "C"),
    "DIMVA": ("Conference on Detection of Intrusions and Malware & Vulnerability Assessment", "C"),
    "DIS": ("ACM SIGCHI Conference on Designing Interactive Systems", "C"),
    "DRM": ("ACM Workshop on Digital Rights Management", "C"),
    "DSAA": ("IEEE International Conference on Data Science and Advanced Analytics", "C"),
    "DSN": ("International Conference on Dependable Systems and Networks", "B"),
    "EASE": ("International Conference on Evaluation and Assessment in Software Engineering", "C"),
    "ECAI": ("European Conference on Artificial Intelligence", "B"),
    "ECCV": ("European Conference on Computer Vision", "B"),
    "ECIR": ("European Conference on Information Retrieval", "C"),
    "ECML-PKDD": ("European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases", "B"),
    "ECOOP": ("European Conference on Object-Oriented Programming", "B"),
    "ECSCW": ("European Conference on Computer Supported Cooperative Work", "B"),
    "EDBT": ("International Conference on Extending Database Technology", "B"),
    "EGSR": ("Eurographics Symposium on Rendering", "B"),
    "EMNLP": ("Conference on Empirical Methods in Natural Language Processing", "B"),
    "EMSOFT": ("International Conference on Embedded Software", "B"),
    "ER": ("International Conference on Conceptual Modeling", "C"),
    "ESA": ("European Symposium on Algorithms", "B"),
    "ESEM": ("International Symposium on Empirical Software Engineering and Measurement", "B"),
    "ESORICS": ("European Symposium on Research in Computer Security", "B"),
    "ESWC": ("Extended Semantic Web Conference", "C"),
    "ETAPS": ("European Joint Conferences on Theory and Practice of Software", "B"),
    "ETS": ("IEEE European Test Symposium", "C"),
    "EUROCRYPT": ("International Conference on the Theory and Applications of Cryptographic Techniques", "A"),
    "Euro-Par": ("European Conference on Parallel and Distributed Computing", "B"),
    "EuroS&P": ("IEEE European Symposium on Security and Privacy", "C"),
    "EuroSys": ("European Conference on Computer Systems", "A"),
    "EuroVis": ("Eurographics Conference on Visualization", "B"),
    "Eurographi\ncs": ("Annual Conference of the European Association for Computer Graphics", "B"),
    "FAST": ("USENIX Conference on File and Storage Technologies", "A"),
    "FC": ("Financial Cryptography and Data Security", "C"),
    "FCCM": ("IEEE Symposium on Field-Programmable Custom Computing Machines", "C"),
    "FG": ("IEEE International Conference on Automatic Face and Gesture Recognition", "C"),
    "FM": ("International Symposium on Formal Methods", "A"),
    "FMCAD": ("Formal Methods in Computer-Aided Design", "C"),
    "FOCS": ("IEEE Annual Symposium on Foundations of Computer Science", "A"),
    "FORTE": ("International Conference on Formal Techniques for Distributed Objects, Components, and Systems", "C"),
    "FPGA": ("ACM/SIGDA International Symposium on Field-Programmable Gate Arrays", "B"),
    "FPL": ("International Conference on Field-Programmable Logic and Applications", "C"),
    "FPT": ("International Conference on Field-Programmable Technology", "C"),
    "FSE": ("Fast Software Encryption", "B"),
    "FSE/ESEC": ("ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering", "A"),
    "FSTTCS": ("Foundations of Software Technology and Theoretical Computer Science", "C"),
    "GECCO": ("Genetic and Evolutionary Computation Conference", "C"),
    "GI": ("Graphics Interface", "C"),
    "GLOBECO\nM": ("IEEE Global Communications Conference", "C"),
    "GLSVLSI": ("Great Lakes Symposium on VLSI", "C"),
    "GMP": ("Geometric Modeling and Processing", "C"),
    "GROUP": ("ACM International Conference on Supporting Group Work", "B"),
    "HCI": ("Human-Computer Interaction", "B"),
    "HOT CHIPS": ("Hot Chips: A Symposium on High Performance Chips", "B"),
    "HOTI": ("IEEE Symposium on High-Performance Interconnects", "C"),
    "HPCA": ("IEEE International Symposium on High Performance Computer Architecture", "A"),
    "HPCC": ("IEEE International Conference on High Performance Computing and Communications", "C"),
    "HPDC": ("The International ACM Symposium on High-Performance Parallel and Distributed Computing", "B"),
    "HSCC": ("International Conference on Hybrid Systems: Computation and Control", "B"),
    "HiPC": ("IEEE International Conference on High Performance Computing, Data and Analytics", "C"),
    "HiPEAC": ("International Conference on High Performance and Embedded Architectures and Compilers", "B"),
    "HotNets": ("ACM The Workshop on Hot Topics in Networks", "C"),
    "HotOS": ("USENIX Workshop on Hot Topics in Operating Systems", "B"),
    "HotSec": ("HotSec", "C"),
    "I3D": ("ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games", "B"),
    "ICA3PP": ("International Conference on Algorithms and Architectures for Parallel Processing", "C"),
    "ICALP": ("International Colloquium on Automata, Languages and Programming", "B"),
    "ICANN": ("International Conference on Artificial Neural Networks", "C"),
    "ICAPS": ("International Conference on Automated Planning and Scheduling", "B"),
    "ICASSP": ("IEEE International Conference on Acoustics, Speech and Signal Processing", "B"),
    "ICC": ("IEEE International Conference on Communications", "C"),
    "ICCAD": ("International Conference on Computer-Aided Design", "B"),
    "ICCBR": ("International Conference on Case-Based Reasoning", "B"),
    "ICCCN": ("IEEE International Conference on Computer Communications and Networks", "C"),
    "ICCD": ("International Conference on Computer Design", "B"),
    "ICCV": ("International Conference on Computer Vision", "A"),
    "ICDAR": ("International Conference on Document Analysis and Recognition", "C"),
    "ICDCS": ("IEEE International Conference on Distributed Computing Systems", "B"),
    "ICDE": ("IEEE International Conference on Data Engineering", "A"),
    "ICDF2C": ("International Conference on Digital Forensics & Cyber Crime", "C"),
    "ICDM": ("IEEE International Conference on Data Mining", "B"),
    "ICDT": ("International Conference on Database Theory", "B"),
    "ICECCS": ("International Conference on Engineering of Complex Computer Systems", "C"),
    "ICFEM": ("International Conference on Formal Engineering Methods", "C"),
    "ICFP": ("ACM SIGPLAN International Conference on Function Programming", "B"),
    "ICIC": ("International Conference on Intelligent Computing", "C"),
    "ICICS": ("International Conference on Information and Communications Security", "C"),
    "ICIP": ("IEEE International Conference on Image Processing", "C"),
    "ICME": ("IEEE International Conference on Multimedia & Expo", "B"),
    "ICMI": ("ACM International Conference on Multimodal Interaction", "C"),
    "ICML": ("International Conference on Machine Learning", "A"),
    "ICMR": ("ACM SIGMM International Conference on Multimedia Retrieval", "B"),
    "ICNP": ("IEEE International Conference on Network Protocols", "B"),
    "ICONIP": ("International Conference on Neural Information Processing", "C"),
    "ICPADS": ("International Conference on Parallel and Distributed Systems", "C"),
    "ICPC": ("IEEE International Conference on Program Comprehension", "B"),
    "ICPP": ("International Conference on Parallel Processing", "B"),
    "ICPR": ("International Conference on Pattern Recognition", "C"),
    "ICRA": ("IEEE International Conference on Robotics and Automation", "B"),
    "ICS": ("International Conference on Supercomputing", "B"),
    "ICSE": ("International Conference on Software Engineering", "A"),
    "ICSME": ("International Conference on Software Maintenance and Evolution", "B"),
    "ICSOC": ("International Conference on Service Oriented Computing", "B"),
    "ICSR": ("International Conference on Software Reuse", "C"),
    "ICSSP": ("International Conference on Software and System Process", "C"),
    "ICST": ("IEEE International Conference on Software Testing, Verification and Validation", "C"),
    "ICTAC": ("International Colloquium on Theoretical Aspects of Computing", "C"),
    "ICTAI": ("IEEE International Conference on Tools with Artificial Intelligence", "C"),
    "ICVRV": ("International Conference on Virtual Reality and Visualization", "C"),
    "ICWE": ("International Conference on Web Engineering", "C"),
    "ICWS": ("IEEE International Conference on Web Services", "B"),
    "ICWSM": ("The International AAAI Conference on Web and Social Media", "B"),
    "IDC": ("ACM Interaction Design and Children", "C"),
    "IEEE BigData": ("IEEE International Conference on Big Data", "C"),
    "IEEE CLOUD": ("IEEE International Conference on Cloud Computing", "C"),
    "IEEE VIS": ("IEEE Visualization Conference", "A"),
    "IFIP WG 11.9": ("IFIP Working Group 11.9 International Conference on Digital Forensics", "C"),
    "IH&MMSec": ("ACM Workshop on Information Hiding and Multimedia Security", "C"),
    "IJCAI": ("International Joint Conference on Artificial Intelligence", "A"),
    "IJCB": ("International Joint Conference on Biometrics", "C"),
    "IJCNN": ("International Joint Conference on Neural Networks", "C"),
    "IJHCI": ("International Journal of Human-Computer Interaction", "B"),
    "IJHCS": ("International Journal of Human-Computer Studies", "A"),
    "ILP": ("International Conference on Inductive Logic Programming", "C"),
    "IM": ("IFIP/IEEE International Symposium on Integrated Network Management", "C"),
    "IMC": ("ACM Internet Measurement Conference", "B"),
    "INFOCOM": ("IEEE International Conference on Computer Communications", "A"),
    "INTERACT": ("International Conference on Human- Computer Interaction of International Federation for Information Processing", "C"),
    "INTERSPEECH": ("Conference of the International Speech Communication Association", "C"),
    "IPCCC": ("IEEE International Performance Computing and Communications Conference", "C"),
    "IPCO": ("International Conference on Integer Programming and Combinatorial Optimization", "C"),
    "IPDPS": ("IEEE International Parallel & Distributed Processing Symposium", "B"),
    "IPSN": ("International Conference on Information Processing in Sensor Networks", "B"),
    "IROS": ("IEEE\\RSJ International Conference on Intelligent Robots and Systems", "C"),
    "ISAAC": ("International Symposium on Algorithms and Computation", "C"),
    "ISBRA": ("International Symposium on Bioinformatics Research and Applications", "C"),
    "ISC": ("Information Security Conference", "C"),
    "ISCA": ("International Symposium on Computer Architecture", "A"),
    "ISCAS": ("IEEE International Symposium on Circuits and Systems", "C"),
    "ISCC": ("IEEE Symposium on Computers and Communications", "C"),
    "ISLPED": ("International Symposium on Low Power Electronics and Design", "C"),
    "ISMAR": ("International Symposium on Mixed and Augmented Reality", "B"),
    "ISMB": ("International conference on Intelligent Systems for Molecular Biology", "B"),
    "ISPA": ("IEEE International Symposium on Parallel and Distributed Processing with Applications", "C"),
    "ISPASS": ("IEEE International Symposium on Performance Analysis of Systems and Software", "C"),
    "ISPD": ("International Symposium on Physical Design", "C"),
    "ISSRE": ("IEEE International Symposium on Software Reliability Engineering", "B"),
    "ISSTA": ("International Symposium on Software Testing and Analysis", "A"),
    "ISWC": ("IEEE International Semantic Web Conference", "B"),
    "ITC": ("International Test Conference", "B"),
    "ITC-Asia": ("International Test Conference in Asia", "C"),
    "ITS": ("ACM International Conference on Interactive Tabletops and Surfaces", "B"),
    "IUI": ("ACM International Conference on Intelligent User Interfaces", "B"),
    "IWC": ("Interacting with Computers", "B"),
    "IWQoS": ("IEEE/ACM International Workshop on Quality of Service", "B"),
    "Inscrypt": ("International Conference on Information Security and Cryptology", "C"),
    "Internetware": ("Asia-Pacific Symposium on Internetware", "C"),
    "KR": ("International Conference on Principles of Knowledge Representation and Reasoning", "B"),
    "KSEM": ("International conference on Knowledge Science, Engineering and Management", "C"),
    "LCN": ("IEEE Conference on Local Computer Networks", "C"),
    "LCTES": ("ACM SIGPLAN/SIGBED International Conference on Languages, Compilers and Tools for Embedded Systems", "B"),
    "LICS": ("ACM/IEEE Symposium on Logic in Computer Science", "A"),
    "LISA": ("Large Installation System Administration Conference", "B"),
    "LOPSTR": ("International Symposium on Logic-based Program Synthesis and Transformation", "C"),
    "MASCOTS": ("International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems", "C"),
    "MASS": ("IEEE International Conference on Mobile Adhoc and Sensor Systems", "C"),
    "MDM": ("International Conference on Mobile Data Management", "C"),
    "MFCS": ("International Conference on Mathematical Foundations of Computer Science", "C"),
    "MICCAI": ("International Conference on Medical Image Computing and Computer-Assisted Intervention", "B"),
    "MICRO": ("IEEE/ACM International Symposium on Microarchitecture", "A"),
    "MMAsia": ("ACM Multimedia Asia", "C"),
    "MMM": ("International Conference on Multimedia Modeling", "C"),
    "MSN": ("International Conference on Mobility, Sensing and Networking", "C"),
    "MSR": ("Mining Software Repositories", "C"),
    "MSST": ("Mass Storage Systems and Technologies", "B"),
    "MSWiM": ("International Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems", "C"),
    "Middleware": ("International Middleware Conference", "B"),
    "MoDELS": ("ACM/IEEE International Conference on Model Driven Engineering Languages and Systems", "B"),
    "MobiCom": ("ACM International Conference on Mobile Computing and Networking", "A"),
    "MobiHoc": ("International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing", "B"),
    "MobiQuitous": ("International Conference on Mobile and Ubiquitous Systems: Computing, Networking and Services", "C"),
    "MobiSys": ("ACM International Conference on Mobile Systems, Applications, and Services", "B"),
    "MobileHCI": ("ACM International Conference on Mobile Human-Computer Interaction", "B"),
    "NAACL": ("North American Chapter of the Association for Computational Linguistics", "B"),
    "NDSS": ("Network and Distributed System Security Symposium", "A"),
    "NLPCC": ("CCF International Conference on Natural Language Processing and Chinese Computing", "C"),
    "NOCS": ("ACM/IEEE International Symposium on Networks-on-Chip", "C"),
    "NOSSDAV": ("International Workshop on Network and Operating System Support for Digital Audio and Video", "B"),
    "NPC": ("IFIP International Conference on Network and Parallel Computing", "C"),
    "NSDI": ("Symposium on Network System Design and Implementation", "A"),
    "NSPW": ("New Security Paradigms Workshop", "C"),
    "Networking": ("IFIP International Conferences on Networking", "C"),
    "NeurIPS": ("Conference on Neural Information Processing Systems", "A"),
    "OOPSLA": ("Conference on Object-Oriented Programming Systems, Languages, and Applications", "A"),
    "OSDI": ("USENIX Symposium on Operating Systems Design and Implementation", "A"),
    "P2P": ("IEEE International Conference on Peer-to-Peer Computing", "C"),
    "PACMHCI": ("Proceedings of the ACM on Human- Computer Interaction", "C"),
    "PACT": ("International Conference on Parallel Architectures and Compilation Techniques", "B"),
    "PAKDD": ("Pacific-Asia Conference on Knowledge Discovery and Data Mining", "C"),
    "PAM": ("Passive and Active Measurement Conference", "C"),
    "PASTE": ("ACMSIGPLAN-SIGSOFT Workshop on Program Analysis for Software Tools and Engineering", "C"),
    "PEPM": ("ACM SIGPLAN Workshop on Partial Evaluation and Program Manipulation", "C"),
    "PERCOM": ("IEEE International Conference on Pervasive Computing and Communications", "B"),
    "PETS": ("Privacy Enhancing Technologies Symposium", "C"),
    "PG": ("Pacific Conference on Computer Graphics and Applications", "B"),
    "PKC": ("International Workshop on Practice and Theory in Public Key Cryptography", "B"),
    "PLDI": ("ACM SIGPLAN Conference on Programming Language Design and Implementation", "A"),
    "PMC": ("Pervasive and Mobile Computing", "C"),
    "PODC": ("ACM Symposium on Principles of Distributed Computing", "B"),
    "PODS": ("ACM SIGMOD-SIGACT-SIGAI Symposium on Principles of Database Systems", "B"),
    "POPL": ("ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages", "A"),
    "PPSN": ("Parallel Problem Solving from Nature", "B"),
    "PPoPP": ("ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming", "A"),
    "PRCV": ("Chinese Conference on Pattern Recognition and Computer Vision (\u4e2d\u56fd\u6a21\u5f0f\u8bc6\u522b\u4e0e\u8ba1\u7b97\u673a\u89c6\u89c9\u5927\u4f1a)", "C"),
    "PRICAI": ("Pacific Rim International Conference on Artificial Intelligence", "C"),
    "PUC": ("Personal and Ubiquitous Computing", "C"),
    "PacificVis": ("IEEE Pacific Visualization Symposium", "C"),
    "Performance": ("International Symposium on Computer Performance, Modeling, Measurements and Evaluation", "B"),
    "QRS": ("International Conference on Software Quality, Reliability and Security", "C"),
    "RAID": ("International Symposium on Recent Advances in Intrusion Detection", "B"),
    "RE": ("IEEE International Requirements Engineering Conference", "B"),
    "RECOMB": ("Annual International Conference on Research in Computational Molecular Biology", "B"),
    "REFSQ": ("Requirements Engineering: Foundation for Software Quality", "C"),
    "RTA": ("International Conference on Rewriting Techniques and Applications", "C"),
    "RTAS": ("IEEE Real-Time and Embedded Technology and Applications Symposium", "B"),
    "RTSS": ("IEEE Real-Time Systems Symposium", "A"),
    "RV": ("International Conference on Runtime Verification", "C"),
    "RecSys": ("ACM Conference on Recommender Systems", "B"),
    "S&P": ("IEEE Symposium on Security and Privacy", "A"),
    "SAC": ("Selected Areas in Cryptography", "C"),
    "SACMAT": ("ACM Symposium on Access Control Models and Technologies", "C"),
    "SAGT": ("International Symposium on Algorithmic Game Theory", "C"),
    "SANER": ("IEEE International Conference on Software Analysis, Evolution, and Reengineering", "B"),
    "SAS": ("International Static Analysis Symposium", "B"),
    "SAT": ("International Conference on Theory and Applications of Satisfiability Testing", "B"),
    "SC": ("International Conference for High Performance Computing, Networking, Storage, and Analysis", "A"),
    "SCA": ("ACM SIGGRAPH/Eurographics Symposium on Computer Animation", "B"),
    "SCAM": ("IEEE International Working Conference on Source Code Analysis and Manipulation", "C"),
    "SCC": ("IEEE International Conference on Services Computing", "C"),
    "SDM": ("SIAM International Conference on Data Mining", "B"),
    "SEC": ("IFIP International Information Security Conference", "C"),
    "SECON": ("IEEE International Conference on Sensing, Communication, and Networking", "B"),
    "SEKE": ("International Conference on Software Engineering and Knowledge Engineering", "C"),
    "SETTA": ("International Symposium on Dependable Software Engineering: Theories, Tools, and Applications", "C"),
    "SGP": ("Eurographics Symposium on Geometry Processing", "B"),
    "SIGCOMM": ("ACM International Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication", "A"),
    "SIGGRAPH": ("ACM Special Interest Group on Computer Graphics", "A"),
    "SIGIR": ("International ACM SIGIR Conference on Research and Development in Information Retrieval", "A"),
    "SIGKDD": ("ACM SIGKDD Conference on Knowledge Discovery and Data Mining", "A"),
    "SIGMETRICS": ("International Conference on Measurement and Modeling of Computer Systems", "B"),
    "SIGMOD": ("ACM SIGMOD Conference", "A"),
    "SIGSPATI\nAL": ("ACM Special Interest Group on Spatial Information", "C"),
    "SMC": ("IEEE International Conference on Systems, Man, and Cybernetics", "C"),
    "SMI": ("Shape Modeling International", "C"),
    "SODA": ("ACM-SIAM Symposium on Discrete Algorithms", "A"),
    "SOSP": ("ACM Symposium on Operating Systems Principles", "A"),
    "SOUPS": ("Symposium On Usable Privacy and Security", "C"),
    "SPAA": ("ACM Symposium on Parallelism in Algorithms and Architectures", "B"),
    "SPIN": ("International Symposium on Model Checking of Software", "C"),
    "SPM": ("Symposium on Solid and Physical Modeling", "B"),
    "SRDS": ("IEEE International Symposium on Reliable Distributed Systems", "B"),
    "SSDBM": ("International Conference on Scientific and Statistical Database Management", "C"),
    "SSTD": ("International Symposium on Spatial and Temporal Databases", "C"),
    "STACS": ("Symposium on Theoretical Aspects of Computer Science", "C"),
    "STOC": ("ACM Symposium on the Theory of Computing", "A"),
    "SYSTOR": ("ACM International Systems and Storage Conference", "C"),
    "SecureComm": ("International Conference on Security and Privacy in Communication Networks", "C"),
    "SenSys": ("ACM Conference on Embedded Networked Sensor Systems", "B"),
    "SoCC": ("ACM Symposium on Cloud Computing", "B"),
    "SoCG": ("International Symposium on Computational Geometry", "B"),
    "TASE": ("Theoretical Aspects of Software Engineering Conference", "C"),
    "TCC": ("Theory of Cryptography Conference", "B"),
    "TOCHI": ("ACM Transactions on Computer-Human Interaction", "A"),
    "TOOLS": ("International Conference on Objects, Models, Components, Patterns\uff082019\u5e74\u505c\u529e\uff09", "C"),
    "TSMC": ("IEEE Transactions on Systems, Man, and Cybernetics: Systems", "B"),
    "TrustCom": ("IEEE International Conference on Trust, Security and Privacy in Computing and Communications", "C"),
    "UAI": ("Conference on Uncertainty in Artificial Intelligence", "B"),
    "UIC": ("IEEE International Conference on Ubiquitous Intelligence and Computing", "C"),
    "UIST": ("ACM Symposium on User Interface Software and Technology", "A"),
    "UMUAI": ("User Modeling and User-Adapted Interaction", "B"),
    "USENIX ATC": ("USENIX Annual Technical Conference", "A"),
    "USENIX Security": ("USENIX Security Symposium", "A"),
    "UbiComp": ("ACM international joint conference on Pervasive and Ubiquitous Computing", "A"),
    "VEE": ("International Conference on Virtual Execution Environments", "B"),
    "VLDB": ("International Conference on Very Large Data Bases", "A"),
    "VMCAI": ("International Conference on Verification, Model Checking and Abstract Interpretation", "B"),
    "VR": ("IEEE Virtual Reality", "A"),
    "VRST": ("ACM Symposium on Virtual Reality Software and Technology", "C"),
    "VTS": ("IEEE VLSI Test Symposium", "C"),
    "WAIM": ("International Conference on Web Age Information Management", "C"),
    "WASA": ("International Conference on Wireless Algorithms, Systems, and Applications", "C"),
    "WCNC": ("IEEE Wireless Communications and Networking Conference", "C"),
    "WICSA": ("Working IEEE/IFIP Conference on Software Architecture", "C"),
    "WINE": ("Conference on Web and Internet Economics", "A"),
    "WISE": ("Web Information Systems Engineering", "C"),
    "WSDM": ("ACM International Conference on Web Search and Data Mining", "B"),
    "WWW": ("International World Wide Web Conference", "A"),
    "WebDB": ("International Workshop on Web and Databases", "C"),
    "WiSec": ("ACM Conference on Security and Privacy in Wireless and Mobile Networks", "C"),
    "WoWMoM": ("IEEE International Symposium on a World of Wireless, Mobile and Multimedia Networks", "C"),
}

CCF_JOURN = {
    "AAMAS": ("Autonomous Agents and Multi-Agent Systems", "B"),
    "ACTA": ("Acta Informatica", "C"),
    "AEI": ("Advanced Engineering Informatics", "B"),
    "AI": ("Artificial Intelligence", "A"),
    "AIM": ("Artificial Intelligence in Medicine", "C"),
    "APAL": ("Annals of Pure and Applied Logic", "C"),
    "ASE": ("Automated Software Engineering", "B"),
    "Algorithmica": ("Algorithmica", "B"),
    "C&G": ("Computers & Graphics", "C"),
    "CAD": ("Computer-Aided Design", "B"),
    "CAGD": ("Computer Aided Geometric Design", "B"),
    "CAVW": ("computer animation & virtual worlds", "C"),
    "CC": ("Computer Communications", "C"),
    "CCF-\nTHPC": ("CCF Transactions on High Performance Computing", "C"),
    "CGF": ("Computer Graphics Forum", "B"),
    "CGTA": ("Computational Geometry: Theory and Applications", "C"),
    "CL": ("Computer Languages, Systems and Structures", "C"),
    "CLSR": ("Computer Law & Security Review", "C"),
    "CN": ("Computer Networks", "B"),
    "CVIU": ("Computer Vision and Image Understanding", "B"),
    "CVMJ": ("Computational Visual Media", "C"),
    "Cognition": ("Cognition", "B"),
    "DAM": ("Discrete Applied Mathematics", "C"),
    "DC": ("Distributed Computing", "C"),
    "DCG": ("Discrete & Computational Geometry", "C"),
    "DKE": ("Data & Knowledge Engineering", "B"),
    "DMKD": ("Data Mining and Knowledge Discovery", "B"),
    "DPD": ("Distributed and Parallel Databases", "C"),
    "DSE": ("Data Science and Engineering", "C"),
    "DSS": ("Decision Support Systems", "C"),
    "EAAI": ("Engineering Applications of Artificial Intelligence", "C"),
    "EJIS": ("European Journal of Information Systems", "B"),
    "ESE": ("Empirical Software Engineering", "B"),
    "ESWA": ("Expert Systems with Applications", "C"),
    "FAC": ("Formal Aspects of Computing", "B"),
    "FCS": ("Frontiers of Computer Science", "B"),
    "FGCS": ("Future Generation Computer Systems", "C"),
    "FITEE": ("Frontiers of Information Technology & Electronic Engineering", "C"),
    "FMSD": ("Formal Methods in System Design", "B"),
    "FUIN": ("Fundamenta Informaticae", "C"),
    "GM": ("Graphical Models", "B"),
    "I&M": ("Information & Management", "C"),
    "IANDC": ("Information and Computation", "A"),
    "IDA": ("Intelligent Data Analysis", "C"),
    "IET-CVI": ("IET Computer Vision", "C"),
    "IET-IPR": ("IET Image Processing", "C"),
    "IETS": ("IET Software", "B"),
    "IJAR": ("International Journal of Approximate Reasoning", "B"),
    "IJCIA": ("International Journal of Computational Intelligence and Applications", "C"),
    "IJCIS": ("International Journal of Cooperative Information Systems", "C"),
    "IJCV": ("International Journal of Computer Vision", "A"),
    "IJDAR": ("International Journal on Document Analysis and Recognition", "C"),
    "IJGIS": ("International Journal of Geographical Information Science", "C"),
    "IJICS": ("International Journal of Information and Computer Security", "C"),
    "IJIS": ("International Journal of Intelligent Systems", "C"),
    "IJISP": ("International Journal of Information Security and Privacy", "C"),
    "IJKM": ("International Journal of Knowledge Management", "C"),
    "IJNS": ("International Journal of Neural Systems", "C"),
    "IJPRAI": ("International Journal of Pattern Recognition and Artificial Intelligence", "C"),
    "IJSEKE": ("International Journal of Software Engineering and Knowledge Engineering", "C"),
    "IJSWIS": ("International Journal on Semantic Web and Information Systems", "C"),
    "IJUFKS": ("International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems", "C"),
    "IMAGE": ("Signal Processing: Image Communication", "C"),
    "IMCS": ("Information and Computer Security", "C"),
    "INFORMS": ("INFORMS Journal on Computing", "B"),
    "IOT": ("IEEE Internet of Things Journal", "C"),
    "IPL": ("Information Processing Letters", "C"),
    "IPM": ("Information Processing and Management", "B"),
    "IR": ("Information Retrieval Journal", "C"),
    "IS": ("Information Systems", "B"),
    "IST": ("Information and Software Technology", "B"),
    "IVC": ("Image and Vision Computing", "C"),
    "Integration": ("Integration, the VLSI Journal", "C"),
    "JACM": ("Journal of the ACM", "A"),
    "JAIR": ("Journal of Artificial Intelligence Research", "B"),
    "JAMIA": ("Journal of the American Medical Informatics Association", "B"),
    "JASA": ("The Journal of the Acoustical Society of America", "B"),
    "JASIST": ("Journal of the Association for Information Science and Technology", "B"),
    "JBHI": ("IEEE Journal of Biomedical and Health Informatics", "C"),
    "JBI": ("Journal of Biomedical Informatics", "C"),
    "JCIS": ("Journal of Computer Information Systems", "C"),
    "JCOMPLEXITY": ("Journal of Complexity", "C"),
    "JCS": ("Journal of Computer Security", "B"),
    "JCSS": ("Journal of Computer and System Sciences", "B"),
    "JCST": ("Journal of Computer Science and Technology", "B"),
    "JDM": ("Journal of Database Management", "C"),
    "JETAI": ("Journal of Experimental and Theoretical Artificial Intelligence", "C"),
    "JETC": ("ACM Journal on Emerging Technologies in Computing Systems", "C"),
    "JETTA": ("Journal of Electronic Testing-Theory and Applications", "C"),
    "JFP": ("Journal of Functional Programming", "B"),
    "JGC": ("Journal of Grid computing", "C"),
    "JGITM": ("Journal of Global Information Technology Management", "C"),
    "JGO": ("Journal of Global Optimization", "B"),
    "JIIS": ("Journal of Intelligent Information Systems", "C"),
    "JISA": ("Journal of Information Security and Applications", "C"),
    "JLAMP": ("Journal of Logical and Algebraic Methods in Programming", "C"),
    "JMLR": ("Journal of Machine Learning Research", "A"),
    "JNCA": ("Journal of Network and Computer Applications", "C"),
    "JPDC": ("Journal of Parallel and Distributed Computing", "B"),
    "JSA": ("Journal of Systems Architecture: Embedded Software Design", "B"),
    "JSAC": ("IEEE Journal on Selected Areas in Communications", "A"),
    "JSC": ("Journal of Symbolic Computation", "B"),
    "JSIS": ("The Journal of Strategic Information Systems", "C"),
    "JSL": ("The Journal of Symbolic Logic", "C"),
    "JSLHR": ("Journal of Speech, Language, and Hearing Research", "B"),
    "JSS": ("Journal of Systems and Software", "B"),
    "JVCIR": ("Journal of Visual Communication and Image Representation", "C"),
    "JWE": ("Journal of Web Engineering", "C"),
    "JWS": ("Journal of Web Semantics", "B"),
    "KAIS": ("Knowledge and Information Systems", "B"),
    "KBS": ("Knowledge-Based Systems", "C"),
    "LISP": ("Higher-Order and Symbolic Computation \uff082013\u5e74\u5df2\u505c\u520a\uff09", "C"),
    "LMCS": ("Logical Methods in Computer Science", "C"),
    "LOGCOM": ("Journal of Logic and Computation", "C"),
    "MICPRO": ("Microprocessors and Microsystems: Embedded Hardware Design", "C"),
    "MONET": ("Mobile Networks and Applications", "C"),
    "MS": ("Multimedia Systems", "C"),
    "MSCS": ("Mathematical Structures in Computer Science", "B"),
    "MTA": ("Multimedia Tools and Applications", "C"),
    "NCA": ("Neural Computing and Applications", "C"),
    "NLE": ("Natural Language Engineering", "C"),
    "NPL": ("Neural Processing Letters", "C"),
    "PAA": ("Pattern Analysis and Applications", "C"),
    "PACM PL": ("Proceedings of the ACM on Programming Languages", "C"),
    "PPNA": ("Peer-to-Peer Networking and Applications", "C"),
    "PR": ("Pattern Recognition", "B"),
    "PRL": ("Pattern Recognition Letters", "C"),
    "Proc. IEEE": ("Proceedings of the IEEE", "A"),
    "RE": ("Requirements Engineering", "B"),
    "RTS": ("Real-Time Systems", "C"),
    "SCIS": ("Science China Information Sciences", "A"),
    "SCN": ("Security and Communication Networks", "C"),
    "SCP": ("Science of Computer Programming", "B"),
    "SICOMP": ("SIAM Journal on Computing", "A"),
    "SIDMA": ("SIAM Journal on Discrete Mathematics", "C"),
    "SIGPRO": ("Signal Processing", "C"),
    "SIIMS": ("SIAM Journal on Imaging Sciences", "B"),
    "SOCA": ("Service Oriented Computing and Applications", "C"),
    "SPE": ("Software: Practice and Experience", "B"),
    "SPECOM": ("Speech Communication", "B"),
    "SPL": ("IEEE Signal Processing Letters", "C"),
    "SQJ": ("Software Quality Journal", "C"),
    "STTT": ("International Journal of Software Tools for Technology Transfer", "C"),
    "STVR": ("Software Testing, Verification and Reliability", "B"),
    "SoSyM": ("Software and Systems Modeling", "B"),
    "TAAS": ("ACM Transactions on Autonomous and Adaptive Systems", "B"),
    "TAC": ("IEEE Transactions on Affective Computing", "B"),
    "TACL": ("Transactions of the Association for Computational Linguistics", "B"),
    "TACO": ("ACM Transactions on Architecture and Code Optimization", "A"),
    "TALG": ("ACM Transactions on Algorithms", "B"),
    "TALLIP": ("ACM Transactions on Asian and Low- Resource Language Information Processing", "C"),
    "TAP": ("ACM Transactions on Applied Perception", "B"),
    "TASAE": ("IEEE Transactions on Automation Science and Engineering", "B"),
    "TASLP": ("IEEE/ACM Transactions on Audio, Speech and Language Processing", "B"),
    "TBD": ("IEEE Transactions on Big Data", "C"),
    "TC": ("IEEE Transactions on Computers", "A"),
    "TCAD": ("IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems", "A"),
    "TCASI": ("IEEE Transactions on Circuits and Systems I: Regular Papers", "C"),
    "TCBB": ("IEEE/ACM Transactions on Computational Biology and Bioinformatics", "B"),
    "TCC": ("IEEE Transactions on Cloud Computing", "C"),
    "TCOM": ("IEEE Transactions on Communications", "B"),
    "TCPS": ("ACM Transactions on Cyber- Physical Systems", "C"),
    "TCS": ("Theoretical Computer Science", "B"),
    "TCSS": ("IEEE Transactions on Computational Social Systems", "C"),
    "TCSVT": ("IEEE Transactions on Circuits and Systems for Video Technology", "B"),
    "TDSC": ("IEEE Transactions on Dependable and Secure Computing", "A"),
    "TEC": ("IEEE Transactions on Evolutionary Computation", "B"),
    "TECS": ("ACM Transactions on Embedded Computing Systems", "B"),
    "TFS": ("IEEE Transactions on Fuzzy Systems", "B"),
    "TG": ("IEEE Transactions on Games", "C"),
    "TGARS": ("IEEE Transactions on Geoscience and Remote Sensing", "B"),
    "TIFS": ("IEEE Transactions on Information Forensics and Security", "A"),
    "TII": ("IEEE Transactions on Industrial Informatics", "C"),
    "TIIS": ("ACM Transactions on Interactive Intelligent Systems", "C"),
    "TIP": ("IEEE Transactions on Image Processing", "A"),
    "TIT": ("IEEE Transactions on Information Theory", "A"),
    "TITS": ("IEEE Transactions on Intelligent Transportation Systems", "B"),
    "TJSC": ("The Journal of Supercomputing", "C"),
    "TKDD": ("ACM Transactions on Knowledge Discovery from Data", "B"),
    "TKDE": ("IEEE Transactions on Knowledge and Data Engineering", "A"),
    "TMC": ("IEEE Transactions on Mobile Computing", "A"),
    "TMI": ("IEEE Transactions on Medical Imaging", "B"),
    "TMM": ("IEEE Transactions on Multimedia", "B"),
    "TNNLS": ("IEEE Transactions on Neural Networks and learning systems", "B"),
    "TNSM": ("IEEE Transactions on Network and Service Management", "C"),
    "TOCE": ("ACM Transactions on Computing Education", "C"),
    "TOCL": ("ACM Transactions on Computational Logic", "B"),
    "TOCS": ("ACM Transactions on Computer Systems", "A"),
    "TODAES": ("ACM Transactions on Design Automation of Electronic Systems", "B"),
    "TODS": ("ACM Transactions on Database Systems", "A"),
    "TOG": ("ACM Transactions on Graphics", "A"),
    "TOIS": ("ACM Transactions on Information Systems", "A"),
    "TOIT": ("ACM Transactions on Internet Technology", "B"),
    "TOMM": ("ACM Transactions on Multimedia Computing, Communications and Applications", "B"),
    "TOMS": ("ACM Transactions on Mathematical Software", "B"),
    "TON": ("IEEE/ACM Transactions on Networking", "A"),
    "TOPLAS": ("ACM Transactions on Programming Languages and Systems", "A"),
    "TOPS": ("ACM Transactions on Privacy and Security", "B"),
    "TOS": ("ACM Transactions on Storage", "A"),
    "TOSEM": ("ACM Transactions on Software Engineering and Methodology", "A"),
    "TOSN": ("ACM Transactions on Sensor Networks", "B"),
    "TPAMI": ("IEEE Transactions on Pattern Analysis and Machine Intelligence", "A"),
    "TPDS": ("IEEE Transactions on Parallel and Distributed Systems", "A"),
    "TPLP": ("Theory and Practice of Logic Programming", "C"),
    "TR": ("IEEE Transactions on Robotics", "B"),
    "TRETS": ("ACM Transactions on Reconfigurable Technology and Systems", "B"),
    "TSC": ("IEEE Transactions on Services Computing", "A"),
    "TSE": ("IEEE Transactions on Software Engineering", "A"),
    "TSLP": ("ACM Transactions on Speech and Language (2013\u5e74\u5df2\u505c\u520a)", "B"),
    "TSUSC": ("IEEE Transactions on Sustainable Computing", "C"),
    "TVC": ("The Visual Computer", "C"),
    "TVCG": ("IEEE Transactions on Visualization and Computer Graphics", "A"),
    "TVLSI": ("IEEE Transactions on Very Large Scale Integration (VLSI) Systems", "B"),
    "TWC": ("IEEE Transactions on Wireless Communications", "B"),
    "TWEB": ("ACM Transactions on the Web", "B"),
    "VLDBJ": ("The VLDB Journal", "A"),
    "WCMC": ("Wireless Communications and Mobile Computing", "C"),
    "WI": ("Web Intelligence", "C"),
    "WWW": ("World Wide Web", "B"),
}
